[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "npm run dev"
  targetPort = 3100
  port = 8888
  framework = "#auto"

[[headers]]
  for = "/map-nodes.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, s-maxage=31536000, must-revalidate"
