import type { CompanyDeepResearchProfile } from "./schema";
import { topCompanyMilestoneSlugs } from "./top-company-milestones";
import { generatedTopCompanyDeepResearchProfiles } from "./top-company-deep-research-profiles";

// Ranks 1-100 preserve the hand-curated prominence cohort audited on 2026-08-02.
// Ranks 101-200 use the documented evidence/activity/readiness score in
// docs/top-200-company-research-audit.md. Keeping the result explicit prevents
// page ordering from drifting as dated records are added elsewhere.
const additionalTopCompanyResearchSlugs = [
  "respicardia", "viz-ai", "elekta", "icometrix", "neuro-event-labs", "nyxoah", "rapidai", "mitsar-eeg",
  "bioserenity", "coapt", "neuronostics", "resolve-stroke", "myomo", "synergia-medical", "omniscient-neurotechnology",
  "samphire-neuroscience", "coherence-neuro", "mjn-neuroserveis", "neuraptive", "positrigo", "wandercraft", "cerebriu",
  "cognision", "imeka", "newronika", "subtle-medical", "cercare-medical", "neurochat-russia", "eneura-edb82",
  "salvia-bioelectronics", "ossur", "cambridge-cognition", "inspire-medical-systems", "longeviti-neuro-solutions", "mon4t",
  "neurinnov", "nico-corporation", "sensome", "wave-neuroscience", "ampa-health", "brainscan-ai", "able-human-motion",
  "linus-health", "neurotrack", "photopharmics", "vielight", "vistim-labs", "x-trodes", "alpha-stim", "braintrip",
  "charco-neurotech", "neuroclues", "axonics", "comphya", "curonix", "ekso-bionics", "epiwatch", "gowerlabs-lumo",
  "graymatters-health", "microtransponder", "neuronic", "qmenta", "qviti", "syntropic", "thymia", "universal-brain",
  "xanastim", "braincapture", "neurobotics-russia", "pixyl", "neurotech-smc", "alto-neuroscience", "aurimod",
  "enspire-dbs-therapy", "machinemd", "naox-technologies", "neurode", "neurolief", "neuronoff", "phagenesis",
  "time-is-brain", "sonavex", "surgical-theater", "brain-navi", "cadence-neuroscience", "ceregate", "encora-therapeutics",
  "galvani-bioelectronics", "kandu", "neosensory", "neuroem-therapeutics", "otolith-labs", "sana-health", "sensars",
  "synaptive-medical", "mobia-medical", "sona", "stimvia", "brainsgate", "marbles-health"
] as const;

export const topCompanyResearchSlugs = [
  ...topCompanyMilestoneSlugs,
  ...additionalTopCompanyResearchSlugs
] as const;

// Generated by scripts/generate-top-company-deep-research.mjs after a live,
// cached source-discovery pass. The checked-in value is intentionally static.
export const topCompanyDeepResearchProfiles: CompanyDeepResearchProfile[] = generatedTopCompanyDeepResearchProfiles;

const profileBySlug = new Map(topCompanyDeepResearchProfiles.map((profile) => [profile.companySlug, profile]));

export const getCompanyDeepResearch = (slug: string): CompanyDeepResearchProfile | undefined =>
  profileBySlug.get(slug);
