// Generates data/world-paths.ts: simplified country outlines projected with a
// plain equirectangular projection into a fixed viewBox. The same projection is
// re-implemented in lib/geo.ts so company markers land in the right place.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { feature } from "topojson-client";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

// Projection constants — keep in sync with lib/geo.ts
export const WIDTH = 1000;
export const HEIGHT = 460;
export const LAT_TOP = 84; // crop the empty top
export const LAT_BOTTOM = -56; // crop Antarctica

function project(lng, lat) {
  const x = ((lng + 180) / 360) * WIDTH;
  const y = ((LAT_TOP - lat) / (LAT_TOP - LAT_BOTTOM)) * HEIGHT;
  return [Math.round(x * 100) / 100, Math.round(y * 100) / 100];
}

function ringToPath(ring) {
  let d = "";
  for (let i = 0; i < ring.length; i++) {
    const [lng, lat] = ring[i];
    const [x, y] = project(lng, lat);
    d += (i === 0 ? "M" : "L") + x + " " + y;
  }
  return d + "Z";
}

function geometryToPath(geom) {
  const { type, coordinates } = geom;
  const polygons = type === "Polygon" ? [coordinates] : coordinates;
  let d = "";
  for (const poly of polygons) {
    for (const ring of poly) {
      d += ringToPath(ring);
    }
  }
  return d;
}

const topo = JSON.parse(readFileSync(join(root, "public", "world-110m.json"), "utf8"));
const geo = feature(topo, topo.objects.countries);

const paths = geo.features
  .map((f, idx) => ({
    id: String(f.id ?? f.properties?.name ?? `c${idx}`),
    name: f.properties?.name ?? "",
    d: geometryToPath(f.geometry)
  }))
  .filter((f) => f.d.length > 0);

const out = `// AUTO-GENERATED by scripts/generate-world.mjs. Do not edit by hand.
export const WORLD_VIEWBOX = "0 0 ${WIDTH} ${HEIGHT}";

export interface CountryPath {
  id: string;
  name: string;
  d: string;
}

export const countryPaths: CountryPath[] = ${JSON.stringify(paths)};
`;

writeFileSync(join(root, "data", "world-paths.ts"), out);
console.log(`Wrote ${paths.length} country paths to data/world-paths.ts`);
